version: '3.8'
services:
  
  api_faba_traning:
    image: api_faba_traning
    container_name: api_faba_traning
    restart: on-failure 
    build:
      dockerfile: build/Dockerfile
      context: .
    ports:
      - 8000:8000
    environment:
      AWSTIO_DB_URL: postgres://postgres:postgres@db_faba_dev:5432/faba_dev?sslmode=disable
      AWSTIO_API_PORT: 8000
      WAIT_HOSTS: db_faba_dev:5432
    networks:
      - new
    depends_on:
      - db_faba_dev    
    links: 
      - db_faba_dev   

  migrate:
    container_name: migrate
    image: migrate/migrate
    depends_on:
      - db_faba_dev
    restart: on-failure  
    networks:
      - new
    volumes:
      - ./migrations:/migrations
    command: -path=/migrations -database postgres://postgres:postgres@db_faba_dev:5432/faba_dev?sslmode=disable up
    links: 
      - db_faba_dev

  db_faba_dev:
    container_name: db_faba_dev
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=faba_dev
    ports:
      - '5432:5432'
    networks:
      new:
        aliases:
          - database      
    volumes: 
      - db:/var/lib/postgresql/data
  
volumes:
  db:
    driver: local
networks:
    new:    
