pkgname="orm"
no-tests="true"
output="internal/databases/orm"
[psql]
  dbname="faba_dev"
  host="localhost"
  port=5432
  user="postgres"
  pass="postgres"
  sslmode="disable"
  blacklist=["schema_migrations"]
  schema="public"