// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"
	request "faba_traning_project/internal/httpbody/request"

	mock "github.com/stretchr/testify/mock"

	response "faba_traning_project/internal/httpbody/response"
)

// IProduct is an autogenerated mock type for the IProduct type
type IProduct struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, requestUser
func (_m *IProduct) Create(ctx context.Context, requestUser request.CreateProduct) (response.Product, error) {
	ret := _m.Called(ctx, requestUser)

	var r0 response.Product
	if rf, ok := ret.Get(0).(func(context.Context, request.CreateProduct) response.Product); ok {
		r0 = rf(ctx, requestUser)
	} else {
		r0 = ret.Get(0).(response.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.CreateProduct) error); ok {
		r1 = rf(ctx, requestUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewIProductT interface {
	mock.TestingT
	Cleanup(func())
}

// NewIProduct creates a new instance of IProduct. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIProduct(t NewIProductT) *IProduct {
	mock := &IProduct{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
