// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"
	models "faba_traning_project/internal/models"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *Repository) Create(ctx context.Context, tx *sql.Tx, _a2 models.Order) (models.Order, error) {
	ret := _m.Called(ctx, tx, _a2)

	var r0 models.Order
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, models.Order) models.Order); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, models.Order) error); ok {
		r1 = rf(ctx, tx, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewRepositoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t NewRepositoryT) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
